### TO JOIN THE TABLES USING A FOREIGN KEY

# The INNER JOIN keyword selects records that have matching values in both tables.

# Joining KINASE table to PHOSPHOSITE TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN PHOSPHOSITE ON PHOSPHOSITE.phosposite_uniprot_id = KINASE.uniprot_id ;''') 
#print(cur.fetchall())

# Joining KINASE table to FAMILY TABLE
cur.execute('''
SELECT Family FROM KINASE INNER JOIN FAMILY ON FAMILY.family_abbreviation = KINASE.Family ;''') 

# Joining KINASE table to ISOFORM TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN ISOFORM ON ISOFORM.isoform_uniprot = KINASE.uniprot_id ;''') 

# Joining KINASE table to DISEASE TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN DISEASE ON DISEASE.uniprot = KINASE.uniprot_id ;''') 

# Joining KINASE table to KINASE_FUNCTION TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN KINASE_FUNCTION ON KINASE_FUNCTION.function_uniprot_id = KINASE.uniprot_id ;''') 

# Joining KINASE table to KINASE_SUBSTRATE TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN KINASE_SUBSTRATE ON KINASE_SUBSTRATE.sub_acc_id = KINASE.uniprot_id ;''')

# Joining KINASE table to REACTIONS TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN REACTIONS ON REACTIONS.reaction_uniprot_id = KINASE.uniprot_id ;''') 

# Joining KINASE table to SUBCELLULAR_LOCATION TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN SUBCELLULAR_LOCATION ON SUBCELLULAR_LOCATION.subcellular_uniprot_id = KINASE.uniprot_id ;''') 

# Joining KINASE table to SUBCELLULAR_ADDITIONAL_TEXT TABLE
cur.execute('''SELECT uniprot_id FROM KINASE INNER JOIN SUBCELLULAR_ADDITIONAL_TEXT ON SUBCELLULAR_ADDITIONAL_TEXT.subcellular_additional_text_uniprot_id = KINASE.uniprot_id ;''') 

# Joining INHIBITOR_GENERAL_INFORMATION table to INHIBITOR_SYNONYMS TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_SYNONYMS INNER JOIN INHIBITOR_GENERAL_INFORMATION ON INHIBITOR_GENERAL_INFORMATION.inn_name = INHIBITOR_SYNONYMS.inn_name ;''') 

# Joining INHIBITOR_GENERAL_INFORMATION table to INHIBITOR_KINASE_FAMILY TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_KINASE_FAMILY INNER JOIN INHIBITOR_GENERAL_INFORMATION ON INHIBITOR_GENERAL_INFORMATION.inn_name = INHIBITOR_KINASE_FAMILY.inn_name ;''') 

# Joining FAMILIES table to INHIBITOR_KINASE_FAMILY TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_KINASE_FAMILY INNER JOIN FAMILY ON FAMILY.family_abbreviation = INHIBITOR_KINASE_FAMILY.inn_name ;''') 

# Joining INHIBITOR_GENERAL_INFORMATION table to INHIBITOR_PDBID TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_PDBID INNER JOIN INHIBITOR_GENERAL_INFORMATION ON INHIBITOR_GENERAL_INFORMATION.inn_name = INHIBITOR_PDBID.inn_name ;''') 

# Joining INHIBITOR_GENERAL_INFORMATION table to INHIBITOR_PDBID TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_PDBID INNER JOIN INHIBITOR_GENERAL_INFORMATION ON INHIBITOR_GENERAL_INFORMATION.inn_name = INHIBITOR_PDBID.inn_name ;''') 

# Joining INHIBITOR_GENERAL_INFORMATION table to INHIBITOR_TARGETS TABLE
cur.execute('''SELECT inn_name FROM INHIBITOR_TARGETS INNER JOIN INHIBITOR_GENERAL_INFORMATION ON INHIBITOR_GENERAL_INFORMATION.inn_name = INHIBITOR_TARGETS.inn_name ;''') 

